### ISSUE TITLE
clean override in Makefile

### ISSUE THREAD

**Issue by Pshriwise** [svalinn/mcnp2cad#17]
It seems that in commit 91b2923e the  typical clean command has been overridden. 

'make CGM_BASE_DIR=<cgm_dir> clean' will now only removes the sphinx build directory (on my machine at least).

**Comment by gonuke** [comment]
Aaah... yes - Line 94 needs to have the `clean` removed

**Comment by Pshriwise** [comment]
Shall I go ahead and take care of that?

**Comment by gonuke** [comment]
You can go ahead and take care of this.  I would do it, but maybe someone with more creativity can take care of  #18 at the same time

**Comment by Pshriwise** [comment]
Alrighty can do.

**Comment by Pshriwise** [comment]
Addressed in #19
