### ISSUE TITLE
over-restrictive CGM_BASE_DIR requirement

### ISSUE THREAD

**Issue by Pshriwise** [svalinn/mcnp2cad#18]
CGM_BASE_DIR is required in the Makefile for any kind of make operation, including those which shouldn't really require the cgm installation (such as cleans, sphinx builds/edits, etc.). I propose this this is altered so that only the .o and mcnp2cad targets require it to be defined.

**Comment by gonuke** [comment]
This might need a little thought than #17 :
* some Makefile magic, or...
* upgrade to autotools/CMake

**Comment by Pshriwise** [comment]
Yes. I'm not entirely sure how to go about this one.. maybe a dependent make target? I'll take a look at this and #17 tomorrow.

**Comment by Pshriwise** [comment]
Addressed in #19
