### ISSUE TITLE
Could we export OCC supported CAD format?

### ISSUE THREAD

**Issue by wangguozhong** [svalinn/mcnp2cad#38]
Hi, everyone! I recently successed to compile the source code with the CGMA library version 15.1. My CGMA library was compiled with OCC library (OCE 0.18).  However, when I execute the app, it tell me that: "ERROR: No geometry exported.  Must set geometry engine to another type." I guess that this is because OCC geometry engine does not support the ACIS's SAT format. So, my issue is could we export OCC supported CAD format? For instance, BREP, STEP. 

Followed is all the output information:

./mcnp2cad tests/INP-box1
Reading input file...
The MCNP title card is: simple box test 
Done reading input.
World size: 7.02619 (trs added 0)
Defining geometry...
Imprinting all...			 done.
Merging, tolerance=1.21697e-06...		 done.
Saving file "out.sat"...			ERROR: No geometry exported.  Must set geometry engine to another type.
 done.

**Comment by gonuke** [comment]
This should work already by using the optional argument to specify an output file:
```
mcnp2cad -o out.step
```
should produce a STEP File.

**Comment by wangguozhong** [comment]
Thank you for your reply. It do work using "-o" option.
