### ISSUE TITLE
Git history inconsistencies

### ISSUE THREAD

**Issue by pshriwise** [svalinn/mcnp2cad#60]
I should have looked at #53 more carefully. There is something quite wrong with the history of our `modular` branch in this repo. The commits PRs #41, #42, #43, and #50 are all missing in the history of that branch and as a result they are no longer in the master branch of this repo either. I'm not sure at what point this happened and I'm not sure what to do about it, but I'll try to come up with a suggestion shortly.

**Comment by pshriwise** [comment]
Perhaps we can just create new PRs and merge them into `master`? Ideally it would all happen in one PR I suppose.

**Comment by gonuke** [comment]
Yikes!  This is probably my fault.  I might have force-pushed the `modular` branch at some point to get things moving??? Although I'm not sure I remember doing that...?

**Comment by pshriwise** [comment]
It could’ve been anyone, really. It may have already been that way when you created #53. Regardless of how it happened, we thankfully have the PR history here to identify what changes need to be re-added.

**Comment by pshriwise** [comment]
I'm leaning toward adding those PRs one-by-one, so their separate purposes are in separate PRs still. (Also, being frank, it's a little easier)

**Comment by pshriwise** [comment]
Looking back at the PR history, these have all been addressed.
